-- Fix existing universities - update type to proper institution types
UPDATE universities 
SET type = CASE 
  WHEN name LIKE '%University of Applied Sciences%' OR name LIKE '%Hochschule%' THEN 'university_applied_sciences'
  WHEN name LIKE '%Technical University%' OR name LIKE '%University of Technology%' THEN 'technical_university'  
  WHEN name LIKE '%Art%' OR name LIKE '%Music%' OR name LIKE '%Design%' THEN 'art_music_university'
  ELSE 'university'
END
WHERE type = 'Public';

-- Insert German Universities (Research Universities)
INSERT INTO universities (name, city, type, control_type, country_code, slug, website) VALUES
('RWTH Aachen University', 'Aachen', 'technical_university', 'public', 'DE', 'rwth-aachen-university', 'https://www.rwth-aachen.de/'),
('University of Augsburg', 'Augsburg', 'university', 'public', 'DE', 'university-of-augsburg', 'https://www.uni-augsburg.de/'),
('University of Bamberg', 'Bamberg', 'university', 'public', 'DE', 'university-of-bamberg', 'https://www.uni-bamberg.de/'),
('University of Bayreuth', 'Bayreuth', 'university', 'public', 'DE', 'university-of-bayreuth', 'https://www.uni-bayreuth.de/'),
('Free University of Berlin', 'Berlin', 'university', 'public', 'DE', 'free-university-of-berlin', 'https://www.fu-berlin.de/'),
('Technical University of Berlin', 'Berlin', 'technical_university', 'public', 'DE', 'technical-university-of-berlin', 'https://www.tu-berlin.de/'),
('University of Bielefeld', 'Bielefeld', 'university', 'public', 'DE', 'university-of-bielefeld', 'https://www.uni-bielefeld.de/'),
('Ruhr University Bochum', 'Bochum', 'university', 'public', 'DE', 'ruhr-university-bochum', 'https://www.rub.de/'),
('University of Bonn', 'Bonn', 'university', 'public', 'DE', 'university-of-bonn', 'https://www.uni-bonn.de/'),
('TU Braunschweig', 'Braunschweig', 'technical_university', 'public', 'DE', 'tu-braunschweig', 'https://www.tu-braunschweig.de/'),
('University of Bremen', 'Bremen', 'university', 'public', 'DE', 'university-of-bremen', 'https://www.uni-bremen.de/'),
('TU Darmstadt', 'Darmstadt', 'technical_university', 'public', 'DE', 'tu-darmstadt', 'https://www.tu-darmstadt.de/'),
('TU Dortmund University', 'Dortmund', 'technical_university', 'public', 'DE', 'tu-dortmund-university', 'https://www.tu-dortmund.de/'),
('TU Dresden', 'Dresden', 'technical_university', 'public', 'DE', 'tu-dresden', 'https://tu-dresden.de/'),
('University of Duisburg-Essen', 'Essen', 'university', 'public', 'DE', 'university-of-duisburg-essen', 'https://www.uni-due.de/'),
('Friedrich-Alexander University Erlangen-Nürnberg', 'Erlangen', 'university', 'public', 'DE', 'friedrich-alexander-university-erlangen-nuernberg', 'https://www.fau.de/'),
('University of Freiburg', 'Freiburg', 'university', 'public', 'DE', 'university-of-freiburg', 'https://www.uni-freiburg.de/'),
('University of Giessen', 'Giessen', 'university', 'public', 'DE', 'university-of-giessen', 'https://www.uni-giessen.de/'),
('University of Göttingen', 'Göttingen', 'university', 'public', 'DE', 'university-of-goettingen', 'https://www.uni-goettingen.de/'),
('University of Halle-Wittenberg', 'Halle', 'university', 'public', 'DE', 'university-of-halle-wittenberg', 'https://www.uni-halle.de/'),
('Leibniz University Hannover', 'Hannover', 'university', 'public', 'DE', 'leibniz-university-hannover', 'https://www.uni-hannover.de/'),
('Heidelberg University', 'Heidelberg', 'university', 'public', 'DE', 'heidelberg-university', 'https://www.uni-heidelberg.de/'),
('University of Hohenheim', 'Stuttgart', 'university', 'public', 'DE', 'university-of-hohenheim', 'https://www.uni-hohenheim.de/'),
('University of Jena', 'Jena', 'university', 'public', 'DE', 'university-of-jena', 'https://www.uni-jena.de/'),
('TU Kaiserslautern', 'Kaiserslautern', 'technical_university', 'public', 'DE', 'tu-kaiserslautern', 'https://www.uni-kl.de/'),
('Karlsruhe Institute of Technology', 'Karlsruhe', 'technical_university', 'public', 'DE', 'karlsruhe-institute-of-technology', 'https://www.kit.edu/'),
('University of Kassel', 'Kassel', 'university', 'public', 'DE', 'university-of-kassel', 'https://www.uni-kassel.de/'),
('University of Kiel', 'Kiel', 'university', 'public', 'DE', 'university-of-kiel', 'https://www.uni-kiel.de/'),
('University of Cologne', 'Cologne', 'university', 'public', 'DE', 'university-of-cologne', 'https://www.uni-koeln.de/'),
('University of Konstanz', 'Konstanz', 'university', 'public', 'DE', 'university-of-konstanz', 'https://www.uni-konstanz.de/'),
('University of Leipzig', 'Leipzig', 'university', 'public', 'DE', 'university-of-leipzig', 'https://www.uni-leipzig.de/'),
('University of Lübeck', 'Lübeck', 'university', 'public', 'DE', 'university-of-luebeck', 'https://www.uni-luebeck.de/'),
('University of Magdeburg', 'Magdeburg', 'university', 'public', 'DE', 'university-of-magdeburg', 'https://www.uni-magdeburg.de/'),
('University of Mainz', 'Mainz', 'university', 'public', 'DE', 'university-of-mainz', 'https://www.uni-mainz.de/'),
('University of Mannheim', 'Mannheim', 'university', 'public', 'DE', 'university-of-mannheim', 'https://www.uni-mannheim.de/'),
('University of Marburg', 'Marburg', 'university', 'public', 'DE', 'university-of-marburg', 'https://www.uni-marburg.de/'),
('LMU Munich', 'Munich', 'university', 'public', 'DE', 'lmu-munich', 'https://www.lmu.de/'),
('University of Münster', 'Münster', 'university', 'public', 'DE', 'university-of-muenster', 'https://www.uni-muenster.de/'),
('University of Oldenburg', 'Oldenburg', 'university', 'public', 'DE', 'university-of-oldenburg', 'https://www.uni-oldenburg.de/'),
('University of Osnabrück', 'Osnabrück', 'university', 'public', 'DE', 'university-of-osnabrueck', 'https://www.uni-osnabrueck.de/'),
('University of Paderborn', 'Paderborn', 'university', 'public', 'DE', 'university-of-paderborn', 'https://www.uni-paderborn.de/'),
('University of Passau', 'Passau', 'university', 'public', 'DE', 'university-of-passau', 'https://www.uni-passau.de/'),
('University of Potsdam', 'Potsdam', 'university', 'public', 'DE', 'university-of-potsdam', 'https://www.uni-potsdam.de/'),
('University of Regensburg', 'Regensburg', 'university', 'public', 'DE', 'university-of-regensburg', 'https://www.uni-regensburg.de/'),
('University of Rostock', 'Rostock', 'university', 'public', 'DE', 'university-of-rostock', 'https://www.uni-rostock.de/'),
('Saarland University', 'Saarbrücken', 'university', 'public', 'DE', 'saarland-university', 'https://www.uni-saarland.de/'),
('University of Siegen', 'Siegen', 'university', 'public', 'DE', 'university-of-siegen', 'https://www.uni-siegen.de/'),
('University of Trier', 'Trier', 'university', 'public', 'DE', 'university-of-trier', 'https://www.uni-trier.de/'),
('University of Tübingen', 'Tübingen', 'university', 'public', 'DE', 'university-of-tuebingen', 'https://www.uni-tuebingen.de/'),
('University of Ulm', 'Ulm', 'university', 'public', 'DE', 'university-of-ulm', 'https://www.uni-ulm.de/'),
('University of Würzburg', 'Würzburg', 'university', 'public', 'DE', 'university-of-wuerzburg', 'https://www.uni-wuerzburg.de/');

-- Insert Universities of Applied Sciences
INSERT INTO universities (name, city, type, control_type, country_code, slug, website) VALUES
('Aachen University of Applied Sciences', 'Aachen', 'university_applied_sciences', 'public', 'DE', 'aachen-university-of-applied-sciences', 'https://www.fh-aachen.de/'),
('Augsburg University of Applied Sciences', 'Augsburg', 'university_applied_sciences', 'public', 'DE', 'augsburg-university-of-applied-sciences', 'https://www.hs-augsburg.de/'),
('Baden-Wuerttemberg Cooperative State University', 'Stuttgart', 'university_applied_sciences', 'public', 'DE', 'baden-wuerttemberg-cooperative-state-university', 'https://www.dhbw.de/'),
('Berlin University of Applied Sciences', 'Berlin', 'university_applied_sciences', 'public', 'DE', 'berlin-university-of-applied-sciences', 'https://www.beuth-hochschule.de/'),
('Bielefeld University of Applied Sciences', 'Bielefeld', 'university_applied_sciences', 'public', 'DE', 'bielefeld-university-of-applied-sciences', 'https://www.fh-bielefeld.de/'),
('Bochum University of Applied Sciences', 'Bochum', 'university_applied_sciences', 'public', 'DE', 'bochum-university-of-applied-sciences', 'https://www.hochschule-bochum.de/'),
('Bonn-Rhein-Sieg University of Applied Sciences', 'Sankt Augustin', 'university_applied_sciences', 'public', 'DE', 'bonn-rhein-sieg-university-of-applied-sciences', 'https://www.h-brs.de/'),
('Brandenburg University of Applied Sciences', 'Brandenburg', 'university_applied_sciences', 'public', 'DE', 'brandenburg-university-of-applied-sciences', 'https://www.th-brandenburg.de/'),
('Bremen University of Applied Sciences', 'Bremen', 'university_applied_sciences', 'public', 'DE', 'bremen-university-of-applied-sciences', 'https://www.hs-bremen.de/'),
('Cologne University of Applied Sciences', 'Cologne', 'university_applied_sciences', 'public', 'DE', 'cologne-university-of-applied-sciences', 'https://www.th-koeln.de/'),
('Darmstadt University of Applied Sciences', 'Darmstadt', 'university_applied_sciences', 'public', 'DE', 'darmstadt-university-of-applied-sciences', 'https://www.h-da.de/'),
('Dortmund University of Applied Sciences', 'Dortmund', 'university_applied_sciences', 'public', 'DE', 'dortmund-university-of-applied-sciences', 'https://www.fh-dortmund.de/'),
('Dresden University of Applied Sciences', 'Dresden', 'university_applied_sciences', 'public', 'DE', 'dresden-university-of-applied-sciences', 'https://www.htw-dresden.de/'),
('Düsseldorf University of Applied Sciences', 'Düsseldorf', 'university_applied_sciences', 'public', 'DE', 'duesseldorf-university-of-applied-sciences', 'https://www.hs-duesseldorf.de/'),
('Erfurt University of Applied Sciences', 'Erfurt', 'university_applied_sciences', 'public', 'DE', 'erfurt-university-of-applied-sciences', 'https://www.fh-erfurt.de/'),
('Esslingen University of Applied Sciences', 'Esslingen', 'university_applied_sciences', 'public', 'DE', 'esslingen-university-of-applied-sciences', 'https://www.hs-esslingen.de/'),
('Frankfurt University of Applied Sciences', 'Frankfurt', 'university_applied_sciences', 'public', 'DE', 'frankfurt-university-of-applied-sciences', 'https://www.frankfurt-university.de/'),
('Fulda University of Applied Sciences', 'Fulda', 'university_applied_sciences', 'public', 'DE', 'fulda-university-of-applied-sciences', 'https://www.hs-fulda.de/'),
('Hamburg University of Applied Sciences', 'Hamburg', 'university_applied_sciences', 'public', 'DE', 'hamburg-university-of-applied-sciences', 'https://www.haw-hamburg.de/'),
('Hannover University of Applied Sciences', 'Hannover', 'university_applied_sciences', 'public', 'DE', 'hannover-university-of-applied-sciences', 'https://www.hs-hannover.de/'),
('Heilbronn University of Applied Sciences', 'Heilbronn', 'university_applied_sciences', 'public', 'DE', 'heilbronn-university-of-applied-sciences', 'https://www.hs-heilbronn.de/'),
('Ingolstadt University of Applied Sciences', 'Ingolstadt', 'university_applied_sciences', 'public', 'DE', 'ingolstadt-university-of-applied-sciences', 'https://www.thi.de/'),
('Karlsruhe University of Applied Sciences', 'Karlsruhe', 'university_applied_sciences', 'public', 'DE', 'karlsruhe-university-of-applied-sciences', 'https://www.hs-karlsruhe.de/'),
('Kiel University of Applied Sciences', 'Kiel', 'university_applied_sciences', 'public', 'DE', 'kiel-university-of-applied-sciences', 'https://www.fh-kiel.de/'),
('Koblenz University of Applied Sciences', 'Koblenz', 'university_applied_sciences', 'public', 'DE', 'koblenz-university-of-applied-sciences', 'https://www.hs-koblenz.de/'),
('Leipzig University of Applied Sciences', 'Leipzig', 'university_applied_sciences', 'public', 'DE', 'leipzig-university-of-applied-sciences', 'https://www.htwk-leipzig.de/'),
('Lübeck University of Applied Sciences', 'Lübeck', 'university_applied_sciences', 'public', 'DE', 'luebeck-university-of-applied-sciences', 'https://www.fh-luebeck.de/'),
('Magdeburg-Stendal University of Applied Sciences', 'Magdeburg', 'university_applied_sciences', 'public', 'DE', 'magdeburg-stendal-university-of-applied-sciences', 'https://www.hs-magdeburg.de/'),
('Mainz University of Applied Sciences', 'Mainz', 'university_applied_sciences', 'public', 'DE', 'mainz-university-of-applied-sciences', 'https://www.hs-mainz.de/'),
('Mannheim University of Applied Sciences', 'Mannheim', 'university_applied_sciences', 'public', 'DE', 'mannheim-university-of-applied-sciences', 'https://www.hs-mannheim.de/'),
('Munich University of Applied Sciences', 'Munich', 'university_applied_sciences', 'public', 'DE', 'munich-university-of-applied-sciences', 'https://www.hm.edu/'),
('Münster University of Applied Sciences', 'Münster', 'university_applied_sciences', 'public', 'DE', 'muenster-university-of-applied-sciences', 'https://www.fh-muenster.de/'),
('Nuremberg Institute of Technology', 'Nuremberg', 'university_applied_sciences', 'public', 'DE', 'nuremberg-institute-of-technology', 'https://www.th-nuernberg.de/'),
('Osnabrück University of Applied Sciences', 'Osnabrück', 'university_applied_sciences', 'public', 'DE', 'osnabrueck-university-of-applied-sciences', 'https://www.hs-osnabrueck.de/'),
('Pforzheim University of Applied Sciences', 'Pforzheim', 'university_applied_sciences', 'public', 'DE', 'pforzheim-university-of-applied-sciences', 'https://www.hs-pforzheim.de/'),
('Rosenheim University of Applied Sciences', 'Rosenheim', 'university_applied_sciences', 'public', 'DE', 'rosenheim-university-of-applied-sciences', 'https://www.th-rosenheim.de/'),
('Stralsund University of Applied Sciences', 'Stralsund', 'university_applied_sciences', 'public', 'DE', 'stralsund-university-of-applied-sciences', 'https://www.hochschule-stralsund.de/'),
('Stuttgart University of Applied Sciences', 'Stuttgart', 'university_applied_sciences', 'public', 'DE', 'stuttgart-university-of-applied-sciences', 'https://www.hft-stuttgart.de/'),
('Ulm University of Applied Sciences', 'Ulm', 'university_applied_sciences', 'public', 'DE', 'ulm-university-of-applied-sciences', 'https://www.thu.de/'),
('Weimar University of Applied Sciences', 'Weimar', 'university_applied_sciences', 'public', 'DE', 'weimar-university-of-applied-sciences', 'https://www.hs-weimar.de/'),
('Würzburg-Schweinfurt University of Applied Sciences', 'Würzburg', 'university_applied_sciences', 'public', 'DE', 'wuerzburg-schweinfurt-university-of-applied-sciences', 'https://www.fhws.de/');

-- Insert some private universities for variety
INSERT INTO universities (name, city, type, control_type, country_code, slug, website) VALUES
('Hertie School', 'Berlin', 'university', 'private', 'DE', 'hertie-school', 'https://www.hertie-school.org/'),
('ESMT Berlin', 'Berlin', 'university', 'private', 'DE', 'esmt-berlin', 'https://www.esmt.org/'),
('Frankfurt School of Finance & Management', 'Frankfurt', 'university_applied_sciences', 'private', 'DE', 'frankfurt-school-of-finance-management', 'https://www.frankfurt-school.de/'),
('WHU – Otto Beisheim School of Management', 'Vallendar', 'university', 'private', 'DE', 'whu-otto-beisheim-school-of-management', 'https://www.whu.edu/'),
('Jacobs University Bremen', 'Bremen', 'university', 'private', 'DE', 'jacobs-university-bremen', 'https://www.jacobs-university.de/'),
('University of Applied Sciences Europe', 'Berlin', 'university_applied_sciences', 'private', 'DE', 'university-of-applied-sciences-europe', 'https://www.ue-germany.com/');