// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfiexgjcuojodmnsinsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmaWV4Z2pjdW9qb2RtbnNpbnN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MTczMjMsImV4cCI6MjA3MTA5MzMyM30.POGAKsZdQXRtshrQbVbuhm2xGz5JO3491yTvn88ipaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});